//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFDemoFull.Lang {
    
    
    public interface ILanguage {
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        global::System.Resources.ResourceManager ResourceManager {
            get;
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        global::System.Globalization.CultureInfo Culture {
            get;
        }
        
        /// <summary>
        ///   查找类似 应用名称 的本地化字符串。
        /// </summary>
        string AppTitle {
            get;
        }
        
        /// <summary>
        ///   查找类似 测试1 的本地化字符串。
        /// </summary>
        string Test1 {
            get;
        }
        
        /// <summary>
        ///  Returns true if the current language is the default language.
        /// </summary>
        bool IsDefault {
            get;
        }
    }
}
